#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "spotdl"
name = "spotDL"
description.en = "Download your Spotify playlists and songs along with album art and metadata (from YouTube if a match is found)."

version = "4.5.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
admindoc = "https://spotdl.readthedocs.io/en/latest/"
userdoc = "https://spotdl.readthedocs.io/en/latest/usage/"
code = "https://github.com/spotDL/spotify-downloader"
fund = "https://github.com/sponsors/Silverarmor"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    # Only used to trigger auto-update
    url = "https://github.com/spotDL/spotify-downloader/releases/download/v4.5.0/spotdl-4.5.0-linux"
    sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    prefetch = false

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3, python3-venv, ffmpeg"
