#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --action="stop" --service="${app}"

#=================================================
# APP CONFIG FILES
#=================================================
ynh_script_progression "Updating $app's configuration files..."

# ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading $app..."

pushd "$install_dir"
    ynh_safe_rm "$install_dir/venv"

    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install spotdl=="$(ynh_app_upstream_version)"

    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/spotdl" --download-deno

    ynh_safe_rm "$install_dir/.cache/pip"
popd


#Logrotate has to be added now, because the app won’t start if there are no logs files
ynh_config_add_logrotate

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}" --template="systemd.service"

yunohost service add "${app}" --description="SpotDL service" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

ynh_systemctl --service="${app}" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"